M48
; DRILL file {KiCad 7.0.2} date Wed Jun 14 22:37:58 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-14T22:37:58-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X2.2179Y-6.0707
X2.2179Y-6.2983
T2
X2.08Y-5.27
X3.02Y-6.8251
X4.8Y-6.8251
X4.8359Y-5.27
T0
M30
